<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ItemDefinitionGroup>
    <Link>
      <AdditionalDependencies Condition="'$(Configuration)|$(Platform)'=='Release|x64'">$(MSBuildThisFileDirectory)lib/cxxbridge1.lib;$(MSBuildThisFileDirectory)lib/rscxx.dll.lib;$(MSBuildThisFileDirectory)lib/rscxx.lib;%(AdditionalDependencies)</AdditionalDependencies>
    </Link>
    <ClCompile>
      <AdditionalIncludeDirectories>$(MSBuildThisFileDirectory)include;%(AdditionalIncludeDirectories)</AdditionalIncludeDirectories>
    </ClCompile>
  </ItemDefinitionGroup>
  <ItemGroup Condition="'$(Configuration)|$(Platform)'=='Release|x64'">
    <ReferenceCopyLocalPaths Include="$(MSBuildThisFileDirectory)bin/rscxx.dll" />
  </ItemGroup>
</Project>
